Repository opensearch-project/job-scheduler, pull requests merged in 2021-12, with the labels that each got.

#109 Bumping job-scheduler to 1.2.2.0
  .github/workflows/test-and-build-workflow.yml
  build.gradle
Labels: v1.2.2

#110 Incremented version to 1.2.3.
  .github/workflows/test-and-build-workflow.yml
  build.gradle
Labels: v1.2.3

#112 Incremented version to 1.2.4.
  .github/workflows/test-and-build-workflow.yml
  build.gradle
Labels: v1.2.4
