Repository opensearch-project/job-scheduler, pull requests merged in 2022-10, with the labels that each got.

#248 [Backport 1.3] Upgrading Cron Utils due to glassfish CVE
  spi/build.gradle
Labels: security vulnerability, backport 1.3

#251 Added groupId as org.opensearch.plugin in pluginZip publication
  build.gradle
Labels: backport 2.x, v2.4.0

#256 Add slf4j which is the dep of cronutils
  spi/build.gradle
Labels: backport 2.x

#261 Adding CI workflow for Windows OS
  .github/workflows/ci.yml
Labels: backport 2.x

#264 Fixing CI workflow
  .github/workflows/ci.yml
Labels: backport 2.x

#267 Added 2.4 release notes
  release-notes/opensearch.job-scheduler.release-notes-2.4.0.0.md
Labels: backport 2.x
