Repository opensearch-project/job-scheduler, pull requests merged in 2023-07, with the labels that each got.

#414 Exclude bwc test for MacOS
  .github/workflows/ci.yml
  sample-extension-plugin/build.gradle
  settings.gradle
Labels: backport 2.x

#417 Force DOCUMENT replication on lock index
  spi/src/main/java/org/opensearch/jobscheduler/spi/utils/LockService.java
  src/test/java/org/opensearch/jobscheduler/multinode/GetLockMultiNodeRestIT.java
Labels: backport 2.x, v2.9.0

#409 fix: time out of range
  src/main/java/org/opensearch/jobscheduler/scheduler/JobScheduler.java
  src/test/java/org/opensearch/jobscheduler/scheduler/JobSchedulerTests.java
Labels: backport 2.x

#428 Add release notes for v2.9.0.0
  release-notes/release-notes/opensearch.job-scheduler.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9
