Repository opensearch-project/job-scheduler, pull requests merged in 2023-08, with the labels that each got.

#432 Fixing release notes path for 2.9
  release-notes/opensearch.job-scheduler.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#435 Call listner.onFailure when lock creation failed
  spi/src/main/java/org/opensearch/jobscheduler/spi/utils/LockService.java
  spi/src/test/java/org/opensearch/jobscheduler/spi/utils/LockServiceIT.java
Labels: backport 2.x

#460 Updating MAINTAINERS.md
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#472 Reverts Document Replication lock index setting
  spi/src/main/java/org/opensearch/jobscheduler/spi/utils/LockService.java
Labels: backport 2.x, v2.10.0

#474 Converts .opendistro-job-scheduler-lock index into a system index
  spi/src/main/java/org/opensearch/jobscheduler/spi/utils/LockService.java
  src/main/java/org/opensearch/jobscheduler/JobSchedulerPlugin.java
Labels: backport 2.x
