Repository opensearch-project/job-scheduler, pull requests merged in 2025-04, with the labels that each got.

#758 [Release 3.0.0-beta1] Add release notes
  release-notes/opensearch-job-scheduler.release-notes-3.0.0.0-beta1.md
Labels: v3.0.0

#767 Remove beta1 qualifier
  build.gradle
Labels: release, v3.0.0, backport main

#770 [Release 3.0.0] Add release notes
  release-notes/opensearch-job-scheduler.release-notes-3.0.0.0.md
Labels: v3.0.0, backport 3.0
